import Foundation

struct Congrats{
    static var congrats:[String] = [
        "You just started",
        "Making progress",
        "U got this",
        "Almost at 100 :)",
        "WOO! 100!",
        "Clicking fast!",
        "💪🏻",
        "Press On!",
        "ALmost at 200!",
        "200!!!",
        "You are above average",
        "Hitting that button fast!",
        "This is a good score!",
        "almost at 300",
        "300!!!!",
        "You are a fast clicker!",
        "You are definitely fast",
        "You are way above average",
        "almost at 400",
        "400!!!!",
        "Wow how do you click so fast",
        "This is extraordinary",
        "Legendary clicks!",
        "almost at 500",
        "500!!!!",
        "Legend",
        "You're spamming",
        "Hacker ;) JK",
        "WOW",
        "almost at 600",
        "600",
        "I am speechless....",
        "This is tooo good to be a human",
        "You are gonna get banned",
        "JK",
        "almost at 700",
        "700!!!"
    ]
}
